// src/constants/jigsawData.ts

export interface JigsawPiece {
  id: string;
  pieceIndex: number; // 0: Top-Left, 1: Top-Right, 2: Bottom-Left, 3: Bottom-Right
  checkpointName: string;
  locationArea: string;
  description: string;
  qrCodeValue: string;
  targetLat: number;
  targetLng: number;
  radiusMeters: number; // รัศมีพิกัดที่ยอมรับได้ (เช่น 500 เมตร)
  hint: string;
}

export interface JigsawQuest {
  id: string;
  title: string;
  badge: string;
  category: string;
  description: string;
  rewardTitle: string;
  rewardDescription: string;
  rewardCode: string;
  fullImageUrl: string;
  gridRows: number;
  gridCols: number;
  pieces: JigsawPiece[];
}

export const MOCK_JIGSAW_QUESTS: JigsawQuest[] = [
  {
    id: "old-town-quest",
    title: "สำรวจเมืองเก่า: ปริศนาแลนด์มาร์คโบราณ",
    badge: "Special Quest",
    category: "Heritage & Culture",
    description: "เดินทางไปยัง 4 จุดสำคัญในย่านเมืองเก่า สแกน QR Code พร้อมเปิด GPS เพื่อรวบรวมชิ้นส่วนจิ๊กซอว์โบราณให้ครบ!",
    rewardTitle: "🏆 ตราประทับเกียรติยศ: ผู้พิทักษ์มรดกเมืองเก่า",
    rewardDescription: "ยินดีด้วย! คุณสะสมจิ๊กซอว์ครบทั้ง 4 ชิ้น ปลดล็อกภาพสมบูรณ์และรับส่วนลดพิเศษ 20% สำหรับร้านค้าพันธมิตร",
    rewardCode: "CLIPPI-HERITAGE-2026",
    // รูปภาพความละเอียดสูงสำหรับนำมาตัดแบ่งจิ๊กซอว์
    fullImageUrl: "https://images.unsplash.com/photo-1508009603885-50cf7c579365?w=1000&auto=format&fit=crop&q=80",
    gridRows: 2,
    gridCols: 2,
    pieces: [
      {
        id: "p1",
        pieceIndex: 0,
        checkpointName: "ซุ้มประตูเมืองเก่า",
        locationArea: "เขตพระนคร กรุงเทพฯ",
        description: "สแกน QR Code บริเวณป้ายบอกทางด้านข้างซุ้มประตูเมืองเก่า",
        qrCodeValue: "CLIPPI-JIGSAW-OLDTOWN-P1",
        targetLat: 13.7563,
        targetLng: 100.5018,
        radiusMeters: 500,
        hint: "ตั้งอยู่ทางทิศเหนือของแนวกำแพงเมืองเก่า สังเกตซุ้มประตูอิฐสีส้ม",
      },
      {
        id: "p2",
        pieceIndex: 1,
        checkpointName: "ศาลเจ้าไม้สักทองโบราณ",
        locationArea: "ถนนเจริญกรุง",
        description: "สแกน QR Code ตรงทางเข้าซุ้มเสาแดงของศาลเจ้า",
        qrCodeValue: "CLIPPI-JIGSAW-OLDTOWN-P2",
        targetLat: 13.7540,
        targetLng: 100.4990,
        radiusMeters: 500,
        hint: "ศาลเจ้าสถาปัตยกรรมจีนโบราณอายุกว่า 120 ปี",
      },
      {
        id: "p3",
        pieceIndex: 2,
        checkpointName: "ร้านกาแฟคั่วโบราณริมคลอง",
        locationArea: "ชุมชนริมคลองโอ่งอ่าง",
        description: "สแกน QR Code ที่เคาน์เตอร์กาแฟโบราณ",
        qrCodeValue: "CLIPPI-JIGSAW-OLDTOWN-P3",
        targetLat: 13.7570,
        targetLng: 100.5040,
        radiusMeters: 500,
        hint: "ร้านเรือนไม้ริมคลองที่มีกลิ่นหอมของกาแฟโบราณคั่วสด",
      },
      {
        id: "p4",
        pieceIndex: 3,
        checkpointName: "ลานกิจกรรมใต้ต้นไทรใหญ่",
        locationArea: "สวนสาธารณะเมืองเก่า",
        description: "สแกน QR Code บนป้ายข้อมูลทางประวัติศาสตร์ใต้ต้นไทร",
        qrCodeValue: "CLIPPI-JIGSAW-OLDTOWN-P4",
        targetLat: 13.7525,
        targetLng: 100.5030,
        radiusMeters: 500,
        hint: "ลานกว้างร่มรื่นที่มีต้นไทรใหญ่อายุเกิน 100 ปี",
      },
    ],
  },
  {
    id: "kanto-sweets-quest",
    title: "ตามล่าขนมร้อยปี: ตะลุยย่านคันโต",
    badge: "Gourmet Quest",
    category: "Sweets & Cafe",
    description: "ออกตามหา 4 ร้านขนมโบราณอายุกว่าร้อยปีในแถบคันโตและจิบะ สแกนรับชิ้นส่วนจิ๊กซอว์ภาพของหวานญี่ปุ่นระดับตำนาน!",
    rewardTitle: "🏆 ตราประทับ: จอมยุทธ์ขนมหวานคันโต + ฟรีชาเขียว 1 แก้ว",
    rewardDescription: "ยินดีด้วย! คุณสะสมจิ๊กซอว์ร้านขนมร้อยปีครบทั้ง 4 ชิ้น ปลดล็อกภาพสมบูรณ์และรับสิทธิพิเศษเครื่องดื่มฟรี!",
    rewardCode: "CLIPPI-SWEETS-KANTO",
    fullImageUrl: "https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=1000&auto=format&fit=crop&q=80",
    gridRows: 2,
    gridCols: 2,
    pieces: [
      {
        id: "k1",
        pieceIndex: 0,
        checkpointName: "ร้านขนม Kimuraya (Chiba City)",
        locationArea: "เมืองจิบะ จังหวัดจิบะ",
        description: "สแกน QR Code บริเวณหน้าร้านขนมโมนาโกะโบราณ Kimuraya",
        qrCodeValue: "CLIPPI-JIGSAW-KANTO-K1",
        targetLat: 35.6074,
        targetLng: 140.1065,
        radiusMeters: 500,
        hint: "ร้านขนมญี่ปุ่นดั้งเดิมที่ก่อตั้งตั้งแต่ปี 1917 ขึ้นชื่อเรื่อง Chiba Monaka",
      },
      {
        id: "k2",
        pieceIndex: 1,
        checkpointName: "Toraya Wagashi Pavilion (Ginza)",
        locationArea: "ย่านกินซ่า โตเกียว",
        description: "สแกน QR Code ใกล้ป้ายร้านวากาชิโบราณ Toraya",
        qrCodeValue: "CLIPPI-JIGSAW-KANTO-K2",
        targetLat: 35.6719,
        targetLng: 139.7648,
        radiusMeters: 500,
        hint: "ร้านขนมโยกังระดับตำนานที่เสิร์ฟในราชสำนักญี่ปุ่นมากว่า 500 ปี",
      },
      {
        id: "k3",
        pieceIndex: 2,
        checkpointName: "Fugetsudo Senbei House (Ueno)",
        locationArea: "ย่านอุเอโนะ โตเกียว",
        description: "สแกน QR Code บริเวณตู้กระจกแสดงขนมโกเฟรต",
        qrCodeValue: "CLIPPI-JIGSAW-KANTO-K3",
        targetLat: 35.7075,
        targetLng: 139.7735,
        radiusMeters: 500,
        hint: "ร้านขนมแผ่นเวเฟอร์กรอบสอดไส้ครีมสไตล์โตเกียวโบราณ",
      },
      {
        id: "k4",
        pieceIndex: 3,
        checkpointName: "Eitaro Sohonpo (Nihonbashi)",
        locationArea: "ย่านนิฮงบาชิ โตเกียว",
        description: "สแกน QR Code หน้าทางเข้าร้านขนมหวานริมแม่น้ำ",
        qrCodeValue: "CLIPPI-JIGSAW-KANTO-K4",
        targetLat: 35.6833,
        targetLng: 139.7745,
        radiusMeters: 500,
        hint: "ผู้ริเริ่มลูกอมน้ำตาลทรายแดงและคินสึบะแห่งสะพานนิฮงบาชิ",
      },
    ],
  },
  {
    id: "kyoto-heritage-quest",
    title: "มนต์เสน่ห์เกียวโต: ปริศนาศาลเจ้าโบราณ",
    badge: "Kyoto Classic",
    category: "Shrines & Temples",
    description: "เยือน 4 จุดแลนด์มาร์คสำคัญในเกียวโต สแกนรับชิ้นส่วนจิ๊กซอว์ซุ้มประตูโทริอิพันต้นและสวนหินเซนเพื่อพิชิตเควสต์!",
    rewardTitle: "🏆 ตราประทับ: ผู้พิทักษ์สายหมอกเกียวโต + รับของที่ระลึก",
    rewardDescription: "ยินดีด้วย! คุณสะสมจิ๊กซอว์ศาลเจ้าเกียวโตครบทั้ง 4 ชิ้น ได้รับตราประทับเกียรติยศและของที่ระลึกสุดลิมิเต็ด",
    rewardCode: "CLIPPI-KYOTO-TEMPLE",
    fullImageUrl: "https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?w=1000&auto=format&fit=crop&q=80",
    gridRows: 2,
    gridCols: 2,
    pieces: [
      {
        id: "ky1",
        pieceIndex: 0,
        checkpointName: "ซุ้มประตูโทริอิ Fushimi Inari",
        locationArea: "เขตฟุชิมิ เกียวโต",
        description: "สแกน QR Code ทางขึ้นอุโมงค์เสาโทริอิสีชาด",
        qrCodeValue: "CLIPPI-JIGSAW-KYOTO-KY1",
        targetLat: 34.9671,
        targetLng: 135.7727,
        radiusMeters: 500,
        hint: "ศาลเจ้าจิ้งจอกขาวที่มีเสาโทริอิสีส้มแดงทอดยาวนับพันต้น",
      },
      {
        id: "ky2",
        pieceIndex: 1,
        checkpointName: "โคมไฟแดงศาลเจ้า Yasaka",
        locationArea: "ย่านกิออน เกียวโต",
        description: "สแกน QR Code ซุ้มประตูทิศตะวันตกศาลเจ้ายาซากะ",
        qrCodeValue: "CLIPPI-JIGSAW-KYOTO-KY2",
        targetLat: 35.0037,
        targetLng: 135.7785,
        radiusMeters: 500,
        hint: "ศาลเจ้าใจกลางย่านกิออนที่ประดับโคมไฟระยิบระยับในยามค่ำคืน",
      },
      {
        id: "ky3",
        pieceIndex: 2,
        checkpointName: "ระเบียงไม้วัด Kiyomizu-dera",
        locationArea: "เขตฮิกาชิยามะ เกียวโต",
        description: "สแกน QR Code หน้าทางเข้าลานชมวิวน้ำตกศักดิ์สิทธิ์",
        qrCodeValue: "CLIPPI-JIGSAW-KYOTO-KY3",
        targetLat: 34.9949,
        targetLng: 135.7850,
        radiusMeters: 500,
        hint: "วัดน้ำใสที่มีระเบียงไม้สร้างโดยไม่ใช้ตะปูแม้แต่ตัวเดียว",
      },
      {
        id: "ky4",
        pieceIndex: 3,
        checkpointName: "สวนหินเซนวัด Ryoan-ji",
        locationArea: "เขตอุเคียว เกียวโต",
        description: "สแกน QR Code บริเวณชานระเบียงชมสวนหินแห้ง",
        qrCodeValue: "CLIPPI-JIGSAW-KYOTO-KY4",
        targetLat: 35.0345,
        targetLng: 135.7182,
        radiusMeters: 500,
        hint: "สวนหินปริศนา 15 ก้อนที่มองจากมุมไหนก็จะเห็นไม่ครบ 15 ก้อน",
      },
    ],
  },
  {
    id: "tokyo-landmarks-quest",
    title: "มหานครโตเกียว: มิติใหม่แห่งแลนด์มาร์ค",
    badge: "Tokyo Modern",
    category: "Landmarks & Culture",
    description: "ท่องมหานครสุดล้ำ สแกนเก็บชิ้นส่วนจิ๊กซอว์แลนด์มาร์คยุคใหม่ตั้งแต่โตเกียวทาวเวอร์จนถึงสกายทรี!",
    rewardTitle: "🏆 ตราประทับ: จ้าวแห่งมหานครโตเกียว + บัตรกำนัล 25%",
    rewardDescription: "ยินดีด้วย! คุณสะสมจิ๊กซอว์แลนด์มาร์คโตเกียวครบทั้ง 4 ชิ้น ได้รับตราประทับเกียรติยศและส่วนลดพิเศษสำหรับการเดินทาง",
    rewardCode: "CLIPPI-TOKYO-2026",
    fullImageUrl: "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1000&auto=format&fit=crop&q=80",
    gridRows: 2,
    gridCols: 2,
    pieces: [
      {
        id: "t1",
        pieceIndex: 0,
        checkpointName: "โตเกียวทาวเวอร์ (Tokyo Tower)",
        locationArea: "เขตมินาโตะ โตเกียว",
        description: "สแกน QR Code บริเวณโถงทางเข้าชั้น 1 ด้านใต้หอคอย",
        qrCodeValue: "CLIPPI-JIGSAW-TOKYO-T1",
        targetLat: 35.6586,
        targetLng: 139.7454,
        radiusMeters: 500,
        hint: "หอคอยโครงเหล็กสีส้มขาวสัญลักษณ์อมตะแห่งมหานครโตเกียว",
      },
      {
        id: "t2",
        pieceIndex: 1,
        checkpointName: "5 แยกชิบูย่า & อนุสาวรีย์ฮาจิโกะ",
        locationArea: "ย่านชิบูย่า โตเกียว",
        description: "สแกน QR Code ด้านข้างรูปปั้นสุนัขยอดกตัญญูฮาจิโกะ",
        qrCodeValue: "CLIPPI-JIGSAW-TOKYO-T2",
        targetLat: 35.6595,
        targetLng: 139.7005,
        radiusMeters: 500,
        hint: "จุดนัดพบยอดนิยมหน้าสถานีชิบูย่า ใกล้ทางข้ามม้าลายที่มีคนข้ามมากที่สุดในโลก",
      },
      {
        id: "t3",
        pieceIndex: 2,
        checkpointName: "โตเกียวสกายทรี (Tokyo Skytree)",
        locationArea: "เขตสุมิดะ โตเกียว",
        description: "สแกน QR Code ลานกว้างชั้น 4 ทางขึ้นจุดชมวิว",
        qrCodeValue: "CLIPPI-JIGSAW-TOKYO-T3",
        targetLat: 35.7100,
        targetLng: 139.8107,
        radiusMeters: 500,
        hint: "หอคอยกระจายเสียงที่สูงที่สุดในโลก สูงตระหง่าน 634 เมตร",
      },
      {
        id: "t4",
        pieceIndex: 3,
        checkpointName: "ย่านเครื่องใช้ไฟฟ้าอากิฮาบาระ (Akihabara)",
        locationArea: "เขตชิโยดะ โตเกียว",
        description: "สแกน QR Code หน้าทางออก Electric Town สถานีอากิฮาบาระ",
        qrCodeValue: "CLIPPI-JIGSAW-TOKYO-T4",
        targetLat: 35.6983,
        targetLng: 139.7731,
        radiusMeters: 500,
        hint: "ดินแดนแห่งแสงสี ป๊อปคัลเจอร์ เกม อนิเมะ และเทคโนโลยี",
      },
    ],
  },
  {
    id: "osaka-food-quest",
    title: "โอซาก้าเมืองแห่งของกิน: ตะลุยกินถิ่นคันไซ",
    badge: "Food Paradise",
    category: "Gourmet & History",
    description: "เยือนเมืองหลวงแห่งสตรีทฟู้ดญี่ปุ่น สแกนรับชิ้นส่วนจิ๊กซอว์ป้ายไฟกูลิโกะ ตลาดคุโรมง และปราสาทโอซาก้า!",
    rewardTitle: "🏆 ตราประทับ: ราชาแห่งโอซาก้า + ทาโกะยากิฟรี 1 ชุด",
    rewardDescription: "ยินดีด้วย! คุณสะสมจิ๊กซอว์โอซาก้าครบทั้ง 4 ชิ้น ปลดล็อกภาพสมบูรณ์และรับคูปองทานทาโกะยากิฟรี 1 ชุด!",
    rewardCode: "CLIPPI-OSAKA-TAKO",
    fullImageUrl: "https://images.unsplash.com/photo-1590559899731-a382839e5549?w=1000&auto=format&fit=crop&q=80",
    gridRows: 2,
    gridCols: 2,
    pieces: [
      {
        id: "o1",
        pieceIndex: 0,
        checkpointName: "ป้ายไฟกูลิโกะแมน โดทงโบริ (Glico Sign)",
        locationArea: "ย่านโดทงโบริ โอซาก้า",
        description: "สแกน QR Code บริเวณสะพานเอบิสึ หน้าป้ายนักวิ่งกูลิโกะ",
        qrCodeValue: "CLIPPI-JIGSAW-OSAKA-O1",
        targetLat: 34.6687,
        targetLng: 135.5013,
        radiusMeters: 500,
        hint: "สะพานคนเดินยอดฮิตริมคลองโดทงโบริที่มีป้ายนักวิ่งชูมือเข้าเส้นชัย",
      },
      {
        id: "o2",
        pieceIndex: 1,
        checkpointName: "ตลาดปลาและอาหารสดคุโรมง (Kuromon)",
        locationArea: "เขตจูโอ โอซาก้า",
        description: "สแกน QR Code หน้าซุ้มทางเข้าตลาดคุโรมง",
        qrCodeValue: "CLIPPI-JIGSAW-OSAKA-O2",
        targetLat: 34.6653,
        targetLng: 135.5073,
        radiusMeters: 500,
        hint: "ครัวแห่งโอซาก้า แหล่งรวมอาหารทะเลสด ซูชิ และเนื้อวากิวเสียบไม้ย่างหอมกรุ่น",
      },
      {
        id: "o3",
        pieceIndex: 2,
        checkpointName: "หอคอยปราสาทโอซาก้า (Osaka Castle)",
        locationArea: "สวนปราสาทโอซาก้า",
        description: "สแกน QR Code บริเวณลานด้านหน้าทางเข้าตัวปราสาทหลัก",
        qrCodeValue: "CLIPPI-JIGSAW-OSAKA-O3",
        targetLat: 34.6873,
        targetLng: 135.5262,
        radiusMeters: 500,
        hint: "ปราสาทหินโบราณที่มีประวัติศาสตร์ยาวนาน สร้างโดยโทโยโทมิ ฮิเดโยชิ",
      },
      {
        id: "o4",
        pieceIndex: 3,
        checkpointName: "หอคอยซึเทนคาคุและย่านชินเซไก (Tsutenkaku)",
        locationArea: "ย่านชินเซไก โอซาก้า",
        description: "สแกน QR Code โคนเสาหอคอยซึเทนคาคุ",
        qrCodeValue: "CLIPPI-JIGSAW-OSAKA-O4",
        targetLat: 34.6525,
        targetLng: 135.5063,
        radiusMeters: 500,
        hint: "หอคอยย้อนยุคใจกลางย่านคุชิคัตสึที่มีรูปปั้นบิลลิเคนแห่งความโชคดี",
      },
    ],
  },
  {
    id: "fuji-nature-quest",
    title: "มนต์เสน่ห์ฟูจิซัง: ทะเลสาบและทิวทัศน์ศักดิ์สิทธิ์",
    badge: "Fuji Adventure",
    category: "Nature & Views",
    description: "ชมวิวฟูจิซังรอบทิศทาง เก็บชิ้นส่วนจิ๊กซอว์เจดีย์แดงชูเรโตะ ทะเลสาบคาวากุจิโกะ และหมู่บ้านน้ำใสโอชิโนะ!",
    rewardTitle: "🏆 ตราประทับ: ผู้พิชิตสายหมอกฟูจิซัง + คูปองกระเช้าลอยฟ้า",
    rewardDescription: "ยินดีด้วย! คุณสะสมจิ๊กซอว์ฟูจิซังครบทั้ง 4 ชิ้น ปลดล็อกภาพทัศนียภาพสมบูรณ์และรับส่วนลดพิเศษสำหรับกระเช้าลอยฟ้า",
    rewardCode: "CLIPPI-FUJI-PEAK",
    fullImageUrl: "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=1000&auto=format&fit=crop&q=80",
    gridRows: 2,
    gridCols: 2,
    pieces: [
      {
        id: "f1",
        pieceIndex: 0,
        checkpointName: "เจดีย์แดงชูเรโตะ (Chureito Pagoda)",
        locationArea: "สวนอาราคุระยามะ จังหวัดยามานาชิ",
        description: "สแกน QR Code จุดชมวิวมุมมหาชนด้านหลังเจดีย์ห้าชั้น",
        qrCodeValue: "CLIPPI-JIGSAW-FUJI-F1",
        targetLat: 35.5013,
        targetLng: 138.8016,
        radiusMeters: 500,
        hint: "มุมถ่ายภาพระดับโลกที่มองเห็นเจดีย์แดงคู่กับภูเขาไฟฟูจิ",
      },
      {
        id: "f2",
        pieceIndex: 1,
        checkpointName: "สวนโออิชิ ริมทะเลสาบคาวากุจิโกะ",
        locationArea: "ฟูจิคาวากุจิโกะ ยามานาชิ",
        description: "สแกน QR Code ริมทางเดินแปลงดอกไม้เลียบทะเลสาบ",
        qrCodeValue: "CLIPPI-JIGSAW-FUJI-F2",
        targetLat: 35.5234,
        targetLng: 138.7460,
        radiusMeters: 500,
        hint: "สวนริมทะเลสาบที่มีทุ่งลาเวนเดอร์และพุ่มโคเชียสะท้อนเงาฟูจิ",
      },
      {
        id: "f3",
        pieceIndex: 2,
        checkpointName: "หมู่บ้านน้ำใสโบราณ โอชิโนะฮักไก",
        locationArea: "หมู่บ้านโอชิโนะ ยามานาชิ",
        description: "สแกน QR Code บริเวณสะพานไม้ข้ามบ่อน้ำศักดิ์สิทธิ์",
        qrCodeValue: "CLIPPI-JIGSAW-FUJI-F3",
        targetLat: 35.4599,
        targetLng: 138.8328,
        radiusMeters: 500,
        hint: "บ่อน้ำธรรมชาติ 8 บ่อที่เกิดจากการละลายของหิมะบนภูเขาไฟฟูจิไหลกรองผ่านชั้นหินลาวา",
      },
      {
        id: "f4",
        pieceIndex: 3,
        checkpointName: "จุดชมวิวกระเช้าลอยฟ้าฟูจิพานอรามา",
        locationArea: "เขากระต่าย เทนโจยามะ",
        description: "สแกน QR Code ดาดฟ้าชมวิวมุมสูง 360 องศา",
        qrCodeValue: "CLIPPI-JIGSAW-FUJI-F4",
        targetLat: 35.5042,
        targetLng: 138.7725,
        radiusMeters: 500,
        hint: "จุดชมวิวมุมสูงมองเห็นทั้งทะเลสาบคาวากุจิโกะและภูเขาไฟฟูจิเต็มตา",
      },
    ],
  },
];

